apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-2
  labels:
    app: nginx-2
spec:
  selector:
    matchLabels:
      app: nginx-2
  template:
    metadata:
      labels:
        app: nginx-2
    spec:
      containers:
        - name: nginx-2
          image: nginx:latest
          ports:
          - containerPort: 80
      initContainers:
        - name: busybox-service
          image: busybox
          command: ['sh', '-c', 'until nslookup service-nginx-2.default.svc.cluster.local; do sleep 5; done;']